Updated deploy script
Promote checks for superfluous new/junior roles to fix up manual promotion of people who don't actually qualify as the rules are written

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -9,14 +9,31 @@ set -o nounset
 # Exit when a piped command returns a non-zero exit code
 set -o pipefail
 
-# Script to rebase the current branch onto the deploy branch
+# Script to tag and push the current version from Cargo.toml
+# $1 is the tag comment. Defaults to something generic if not provided
 
-
-readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )"
+readonly repo_dir="$( cd $(dirname ${BASH_SOURCE}); pwd )";
 cd $repo_dir
 
-readonly original_branch=`git rev-parse --abbrev-ref HEAD`;
-git checkout deploy
-git rebase "$original_branch"
-git push
-git checkout "$original_branch"
+if [ -n "$(git status --porcelain)" ]; then
+    echo "Working directory isn't clean. Please commit or stash outstanding work";
+    exit 1;
+fi
+
+readonly version=`cat Cargo.toml | sed -n '/^version *=* */{s///;s/^"//;s/"$//;p;}'`;
+if [ "$version" == "" ]; then
+    echo "Failed to extract version from Cargo.toml";
+    exit 1;
+fi
+
+readonly tag="v${version}";
+readonly tag_message="${1:-Release of ${tag}}";
+
+read -r -p "About to create and push tag \"${tag}\" with annotation \"${tag_message}\". Continue? [Y/n]" response
+response=${response,,}    # tolower
+if [[ "$response" =~ ^(yes|y|)$ ]]; then
+    git tag -a "${tag}" -m "${tag_message}"
+    git push origin "tags/${tag}"
+else 
+    echo "Aborted"
+fi
